server:
  port: 7779
  
#spring:
#  datasource:
#    driverClassName: org.h2.Driver
#    password: root
#    url: jdbc:h2:mem:admindb
#    username: root
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true

spring:
  application:
    name: ADMIN-SERVICE
  datasource:
    url: jdbc:mysql://useadmindb.cxipmma3xhr1.ap-south-1.rds.amazonaws.com:3306/useadmindb
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate :
        dialect: org.hibernate.dialect.MySQL8Dialect
